// SPDX-License-Identifier: Apache-2.0
/** Browser projection for Rulith Local. It contains no Case or Worker authority. */
/**
 * The Cases this conversation is working, as the Agent observed them.
 *
 * A conversation holds a set of acceptance roots, not one active Case, and each root has
 * its own lifecycle. Membership comes from the Agent's `focus` events, which carry the
 * {caseId, root} pairs the authority returned; lifecycle comes from the per-root
 * `case-state` observations. Neither is inferred here — a projection that guessed a
 * status would be a second, quieter source of truth about the Board.
 *
 * A root that has left focus is still listed while the view remembers it, marked as
 * released: leaving focus is not a lifecycle transition, and neither is a reclaimed local
 * conversation.
 */
export function projectCaseRoots(events) {
  const labels = { running: 'Running', paused: 'Paused', closed: 'Closed' }
  const observed = new Map(), order = [], detached = new Set()
  let focus = null
  for (const event of events) {
    if (event.src !== 'agent') continue
    if (event.type === 'focus' && Array.isArray(event.roots)) {
      focus = event.roots.map((row) => String(row?.caseId ?? '')).filter(Boolean)
    }
    const id = String(event.caseId || '')
    if (!id) continue
    if (event.type === 'case-state') observed.set(id, event)
    if (event.type === 'session-detached') detached.add(id)
    if (['case-state', 'case-closed', 'case-pending', 'session-detached', 'case-unfocused'].includes(event.type)
      || (event.type === 'case-open' && event.ok !== false)) {
      if (!order.includes(id)) order.push(id)
    }
  }
  const focused = focus === null ? order : focus
  const ids = [...focused, ...order.filter((id) => !focused.includes(id))]
  return ids.map((caseId) => {
    const snapshot = observed.get(caseId)
    const lifecycle = Object.hasOwn(labels, snapshot?.caseStatus) ? snapshot.caseStatus : 'unavailable'
    return {
      caseId,
      root: String(snapshot?.root || ''),
      focused: focused.includes(caseId),
      lifecycle,
      label: labels[lifecycle] || 'Unavailable',
      gaps: typeof snapshot?.gaps === 'number' ? snapshot.gaps : null,
      observation: detached.has(caseId) ? 'Detached · last observed'
        : snapshot?.contact === 'unknown' ? 'No authoritative response'
          : snapshot?.contact === 'not-refreshed' ? 'Not refreshed by the last bounded answer'
            : lifecycle === 'unavailable' ? 'Unavailable' : 'Last observed',
    }
  })
}

/**
 * What this conversation is waiting for, in plain words.
 *
 * The Agent may be holding a call whose outcome only the authority knows. That is not an
 * error and it is not idleness, and showing it as either is how a person concludes the
 * Runtime is stuck — or, worse, that nothing was ever dispatched. So it gets its own line:
 * the state the authority published, which tool it concerns, and what the host is doing
 * about it. Nothing is inferred; every field comes from an event the Agent emitted.
 *
 * The states are the authority's four, plus the local blocked outcomes that end a turn.
 * `result_ready` is deliberately visible even though it is usually brief: when the handoff
 * cannot be completed, that brief state is the whole explanation.
 */
export function projectRecovery(events) {
  let current = { state: 'none', label: 'No unresolved call', detail: '', tool: '' }
  for (const event of events) {
    if (event.src !== 'agent') continue
    const tool = String(event.tool || current.tool || '')
    if (event.type === 'recovery') {
      if (event.state === 'none') {
        // The authority says there is nothing outstanding. Without this branch the panel
        // kept showing the last `waiting` for the rest of the session, which reads as a
        // Runtime that never came back.
        current = { state: 'none', tool: '', label: 'No unresolved call', detail: '' }
      } else if (event.state === 'unreadable') {
        current = { state: 'unreadable', tool, label: 'The authority published no readable recovery record',
          detail: 'This host will not start work while it cannot tell whether a call is outstanding.' }
      } else if (event.state === 'claim_not_honoured') {
        current = { state: 'result_ready', tool, label: 'An earlier ' + (tool || 'tool') + ' result was not handed over',
          detail: 'The authority reports a determined result but answered the collecting request as an ordinary query. It is being retried.' }
      } else if (event.state === 'waiting') {
        current = { state: 'waiting', tool, label: 'Waiting for an earlier ' + (tool || 'tool') + ' call',
          detail: 'The authority is still executing it. No model turn and no further call are sent until it settles.' }
      } else if (event.state === 'result_ready') {
        current = { state: 'result_ready', tool, label: 'Collecting an earlier ' + (tool || 'tool') + ' result',
          detail: 'The outcome is determined and is being handed over. The request that collects it executes nothing.' }
      } else if (event.state === 'reconciliation_required') {
        current = { state: 'reconciliation_required', tool, label: 'An earlier ' + (tool || 'tool') + ' call needs operator reconciliation',
          detail: 'Automatic recovery has stopped. Reconcile the original call in Console; waiting does not undo an effect that may have happened.' }
      }
    }
    if (event.type === 'handoff') {
      current = { state: 'none', tool: '', label: 'No unresolved call',
        detail: 'The outcome of an earlier ' + (String(event.tool || 'tool')) + ' call was handed to the model, which decides again.' }
    }
    if (event.type === 'queue-suspended') {
      current = { ...current, detail: event.notSent + ' further call(s) proposed in that turn were not sent.' }
    }
    if (event.type === 'recovery-conflict') {
      current = { state: 'unreconciled', tool: String(event.tool || ''),
        label: 'An earlier ' + String(event.tool || 'tool') + ' call needs reconciling',
        detail: 'Its outcome was never learned and the authority reports nothing outstanding. Reconcile request '
          + String(event.requestId || '') + ' in Console; an empty record does not prove the command had no effect.' }
    }
    if (event.type === 'blocked') {
      current = { state: 'blocked', tool, label: 'Turn stopped: ' + String(event.reason || 'unresolved call'),
        detail: String(event.teaching || '') }
    }
    // A turn that got going again is the clearest possible statement that the gate opened.
    if (event.type === 'propose' && (current.state === 'blocked' || current.state === 'waiting')) {
      current = { state: 'none', tool: '', label: 'No unresolved call', detail: '' }
    }
  }
  return current
}

export const localPage = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Rulith Local</title>
<style>
:root{color-scheme:dark;--bg:#0d0f12;--sidebar:#111317;--panel:#15181d;--panel2:#1b1f25;--line:#292e36;--fg:#eef1f4;--muted:#969da8;--faint:#686f7a;--accent:#48d7c2;--blue:#8eb6ff;--green:#4fd19b;--amber:#e5ad55;--red:#ef7d7d;--radius:12px}
*{box-sizing:border-box}html,body{height:100%;margin:0}body{background:var(--bg);color:var(--fg);font:14px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",system-ui,sans-serif;overflow:hidden}
button,input,textarea,select{font:inherit;color:inherit}button{cursor:pointer}.app{display:grid;grid-template-columns:250px minmax(460px,1fr) 330px;height:100vh}.sidebar,.inspector{background:var(--sidebar);min-width:0}.sidebar{border-right:1px solid var(--line);display:flex;flex-direction:column}.inspector{border-left:1px solid var(--line);overflow:auto}.brand{height:58px;padding:17px 18px;display:flex;align-items:center;gap:10px;font-weight:700;letter-spacing:.2px}.logo{width:17px;height:17px;border-radius:5px;background:var(--accent);box-shadow:0 0 24px rgba(72,215,194,.28)}.mode{font-size:11px;color:var(--muted);border:1px solid var(--line);border-radius:99px;padding:2px 7px;margin-left:auto}.new{margin:6px 12px 16px;width:calc(100% - 24px);border:1px solid #3a4049;background:#22262d;border-radius:9px;padding:9px 12px;text-align:left}.new:hover{background:#292e36}.side-title{padding:0 16px 7px;color:var(--faint);font-size:11px;text-transform:uppercase;letter-spacing:.8px}.cases{overflow:auto;flex:1;padding:0 8px}.case{padding:9px 10px;border-radius:8px;margin:2px 0;color:#c9ced6;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.case:hover,.case.active{background:#20242b;color:#fff}.case small{display:block;color:var(--faint);font-size:11px}.side-foot{border-top:1px solid var(--line);padding:10px 12px}.runtimeid{display:flex;align-items:center;gap:9px;padding:8px;margin-bottom:5px}.avatar{width:27px;height:27px;flex:0 0 27px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#4bcfbc,#4679ca);color:white;font-weight:700}.runtimecopy{min-width:0}.runtimecopy b,.runtimecopy small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.runtimecopy b{font-size:12px}.runtimecopy small{font-size:10px;color:var(--muted)}.statusline{display:flex;align-items:center;gap:8px;padding:4px 8px;color:var(--muted);font-size:11px}.dot{width:7px;height:7px;border-radius:50%;background:var(--faint)}.dot.on{background:var(--green);box-shadow:0 0 10px rgba(79,209,155,.45)}
.main{min-width:0;min-height:0;height:100vh;overflow:hidden;display:flex;flex-direction:column}.top{height:58px;border-bottom:1px solid var(--line);display:flex;align-items:center;padding:0 22px;gap:10px}.title{font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sub{color:var(--muted);font-size:12px}.spacer{flex:1}.views{align-self:stretch;display:flex;align-items:flex-end;gap:15px;margin-left:18px}.viewtab{height:38px;border:0;border-bottom:2px solid transparent;background:transparent;color:var(--muted);padding:0 2px}.viewtab.active{color:var(--fg);border-bottom-color:var(--accent)}.ghost{border:1px solid var(--line);background:transparent;border-radius:8px;padding:6px 10px;color:var(--muted)}.mobile-settings{display:none}.stream{flex:1;min-height:0;overflow:auto;padding:24px max(24px,calc((100% - 790px)/2)) 130px;overscroll-behavior:contain;scrollbar-gutter:stable}.empty{max-width:640px;margin:18vh auto 0;text-align:center;color:var(--muted)}.empty h1{color:var(--fg);font-size:24px;margin:0 0 8px}.message{max-width:780px;margin:0 auto 18px}.user{display:flex;justify-content:flex-end}.bubble{max-width:78%;background:#272b31;border-radius:16px 16px 4px 16px;padding:10px 14px;white-space:pre-wrap}.agent-text{white-space:pre-wrap;color:#e4e7eb}.meta{font-size:11px;color:var(--faint);margin-bottom:5px}.event{border:1px solid var(--line);border-radius:10px;background:var(--panel);overflow:hidden}.event-head{display:flex;gap:9px;align-items:center;padding:9px 11px;color:#cfd4db}.event-head .kind{font-weight:600}.event-head .right{margin-left:auto;color:var(--faint);font-size:11px}.event-body{border-top:1px solid var(--line);padding:9px 11px;color:var(--muted);white-space:pre-wrap;overflow:auto;max-height:230px}.event.good{border-color:rgba(79,209,155,.34)}.event.warn{border-color:rgba(229,173,85,.34)}.event.bad{border-color:rgba(239,125,125,.35)}.ico{width:20px;height:20px;display:inline-grid;place-items:center;border-radius:6px;background:#252a31;color:var(--accent)}
.composer{position:absolute;left:250px;right:330px;bottom:0;padding:12px 24px 18px;background:linear-gradient(transparent,var(--bg) 25%);display:flex;justify-content:center}.composebox{position:relative;width:min(790px,100%);background:#202329;border:1px solid #353a43;border-radius:16px;padding:11px 12px;box-shadow:0 12px 35px rgba(0,0,0,.28)}.composebox>textarea{display:block;width:100%;resize:none;min-height:30px;max-height:150px;border:0;outline:0;background:transparent}.composebar{display:flex;align-items:center;gap:7px;margin-top:8px}.roundbtn{flex:0 0 30px;width:30px;height:30px;border:1px solid var(--line);border-radius:50%;background:transparent;color:var(--muted);font-size:18px;line-height:1}.toolbarbadge,.modelbadge{height:30px;display:inline-flex;align-items:center;min-width:0;border:0;background:transparent;color:var(--muted);font-size:12px}.modelbadge{max-width:185px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:0 6px}.case-pop[hidden]{display:none}.case-pop{position:absolute;left:8px;bottom:54px;width:min(410px,calc(100% - 16px));z-index:3;background:var(--panel);border:1px solid #3a4049;border-radius:11px;padding:12px;box-shadow:0 15px 44px rgba(0,0,0,.45)}.case-pop label{display:block;color:var(--muted);font-size:11px;margin-bottom:9px}.case-pop label:last-child{margin-bottom:0}.case-pop input{display:block;width:100%;margin-top:4px;background:#0e1115;border:1px solid var(--line);border-radius:7px;padding:8px;outline:0}.send{margin-left:auto;flex:0 0 32px;width:32px;height:32px;border:0;border-radius:50%;background:var(--accent);color:#061512;font-weight:800}.send:disabled{opacity:.35}.worker-only .composer{display:none}.worker-only .stream{padding-bottom:24px}
.inspect-head{height:58px;border-bottom:1px solid var(--line);padding:18px 16px;font-weight:600}.section{padding:15px 16px;border-bottom:1px solid var(--line)}.section h3{font-size:11px;text-transform:uppercase;letter-spacing:.75px;color:var(--faint);margin:0 0 10px}.kv{display:flex;gap:8px;justify-content:space-between;margin:6px 0;color:var(--muted)}.kv b{color:var(--fg);font-weight:500;text-align:right}.frontier,.workers{display:grid;gap:7px}.item{background:var(--panel2);border:1px solid var(--line);border-radius:8px;padding:8px 9px;color:#cbd0d7;font-size:12px}.item small{display:block;color:var(--faint);margin-top:3px}.settingsopen{width:100%;border:1px solid var(--line);background:var(--panel2);border-radius:8px;padding:9px 11px;text-align:left}.settingsopen:hover{border-color:#454c58}.modal[hidden]{display:none}.modal{position:fixed;inset:0;z-index:50;background:rgba(0,0,0,.68);display:grid;place-items:center;padding:24px}.modal-card{width:min(820px,96vw);max-height:88vh;overflow:auto;background:var(--panel);border:1px solid #383e48;border-radius:14px;box-shadow:0 24px 80px rgba(0,0,0,.55)}.modal-head{position:sticky;top:0;z-index:2;display:flex;align-items:center;gap:12px;padding:16px 18px;background:var(--panel);border-bottom:1px solid var(--line)}.modal-head b{font-size:16px}.modal-head .sub{display:block}.modal-close{margin-left:auto;width:32px;height:32px;border:1px solid var(--line);background:transparent;border-radius:8px}.runtimegrid{display:grid;grid-template-columns:1fr 1fr}.runtimepane{padding:18px}.runtimepane+ .runtimepane{border-left:1px solid var(--line)}.runtimepane h3{margin:0 0 10px}.runtimepane code{font:12px/1.45 ui-monospace,Consolas,monospace;color:#cbd0d7;word-break:break-all}.runtimecontrols{display:flex;gap:8px;margin-top:14px}.runtimecontrols button{border:1px solid var(--line);background:transparent;border-radius:8px;padding:7px 10px;color:var(--muted)}.runtimefoot{padding:14px 18px;border-top:1px solid var(--line);color:var(--muted);font-size:12px}.runtimefoot code{color:#cbd0d7}
@media(max-width:1050px){.app{grid-template-columns:220px minmax(420px,1fr)}.inspector{display:none}.composer{left:220px;right:0}}@media(max-width:720px){.app{display:block}.sidebar{display:none}.main{height:100vh}.composer{left:0}.top{padding:0 14px}.stream{padding-left:14px;padding-right:14px}.mobile-settings{display:inline-block}.runtimegrid{grid-template-columns:1fr}.runtimepane+ .runtimepane{border-left:0;border-top:1px solid var(--line)}.views{margin-left:4px;gap:9px}.sessionlog{display:none}}
</style></head><body><div class="app" id="app">
<aside class="sidebar"><div class="brand"><span class="logo"></span>Rulith Local<span class="mode" id="mode">…</span></div><button class="new" id="newcase">＋ New conversation</button><div class="side-title">Activity</div><div class="cases" id="cases"><div class="case active" data-case="">All activity</div></div><div class="side-foot"><div class="runtimeid"><span class="avatar">A</span><span class="runtimecopy"><b id="agentname">Configured Agent</b><small id="agentidentity">loading…</small></span></div><button class="settingsopen" id="runtimeopen">◎ Runtime details</button><div class="statusline"><span class="dot" id="agentdot"></span>Agent <span id="agentstate">off</span></div><div class="statusline"><span class="dot" id="workerdot"></span>Worker <span id="workerstate">off</span></div></div></aside>
<main class="main"><header class="top"><div><div class="title" id="title">Local activity</div><div class="sub" id="subtitle">Conversation with optional Rulith Case tools</div></div><nav class="views" aria-label="Activity view"><button class="viewtab active" data-view="case">Conversation</button><button class="viewtab" data-view="trace">Trace</button></nav><span class="spacer"></span><button class="ghost sessionlog" id="exportlog">Session log ↓</button><button class="ghost mobile-settings" id="mobileruntime" title="Runtime details">◎</button><button class="ghost" id="clear">Clear view</button></header><div class="stream" id="stream"><div class="empty" id="empty"><h1>What would you like to discuss or handle?</h1><p>Chat normally. The Agent will use Rulith when governed work, evidence, or an auditable Case is useful.</p></div></div></main>
<aside class="inspector"><div class="inspect-head">Rulith Cases</div><section class="section"><h3>Cases in focus</h3><div class="kv"><span>Acceptance roots</span><b id="casecount">Not in use</b></div><div class="frontier" id="roots"><div class="item">Rulith has not been used for this conversation.</div></div></section><section class="section"><h3>Unresolved call</h3><div class="frontier" id="recovery"><div class="item">No unresolved call</div></div></section><section class="section"><h3>Current frontier</h3><div class="frontier" id="frontier"><div class="item">Rulith has not been used for this conversation.</div></div></section><section class="section"><h3>Worker activity</h3><div class="workers" id="workers"><div class="item">No Worker activity for this conversation.</div></div></section></aside>
<form class="composer" id="composer"><div class="composebox"><textarea id="prompt" placeholder="Message the Agent…" rows="1"></textarea><div class="case-pop" id="casepopover" hidden><label>Preferred Case Type if Rulith is used<input id="casetype" value="exploration" aria-label="Case Type"></label><label>Business key JSON (optional)<input id="businesskey" placeholder='{"job_id":"..."}' aria-label="Business key JSON"></label></div><div class="composebar"><button type="button" class="roundbtn" id="caseoptions" title="Rulith preferences">＋</button><span class="toolbarbadge" id="toolbadge">Rulith available</span><button type="button" class="modelbadge" id="modelbadge" title="Runtime details">Model</button><span class="toolbarbadge" id="thinkingbadge">Standard</span><button class="send" id="send" title="Send message">↑</button></div></div></form>
</div><div class="modal" id="runtimemodal" role="dialog" aria-modal="true" aria-labelledby="runtimetitle" hidden><div class="modal-card"><div class="modal-head"><div><b id="runtimetitle">Runtime details</b><span class="sub">Read-only projection of the single-Agent Runtime configuration. Edit the configuration file or secret manager, then restart the process.</span></div><button class="modal-close" id="runtimeclose" aria-label="Close Runtime details">×</button></div><div class="runtimegrid"><section class="runtimepane"><h3>Agent</h3><div class="kv"><span>Cloud Agent</span><b id="detailagent">—</b></div><div class="kv"><span>Credential</span><b id="detailagentkey">—</b></div><div class="kv"><span>Model service</span><b><code id="detailmodelurl">—</code></b></div><div class="kv"><span>Model</span><b id="detailmodel">—</b></div><div class="kv"><span>Model key</span><b id="detailmodelkey">—</b></div><div class="kv"><span>Reasoning</span><b id="detailthinking">—</b></div><div class="kv"><span>Case calls</span><b id="detailconcurrency">—</b></div><div class="runtimecontrols"><button data-control="agent" data-operation="stop">Stop Agent</button><button data-control="agent" data-operation="start">Start Agent</button></div></section><section class="runtimepane"><h3>Worker</h3><div class="kv"><span>Connection</span><b id="detailconnection">—</b></div><div class="kv"><span>Credential</span><b id="detailworkerkey">—</b></div><div class="kv"><span>Workspace tools</span><b id="detailtools">—</b></div><div class="kv"><span>Tool manifest</span><b><code id="detailtoolsfile">—</code></b></div><div class="kv"><span>Source vault</span><b><code id="detailsourcesfile">—</code></b></div><div class="runtimecontrols"><button data-control="worker" data-operation="stop">Stop Worker</button><button data-control="worker" data-operation="start">Start Worker</button></div></section></div><div class="runtimefoot">Configuration: <code id="detailconfig">—</code><div id="runtimemsg"></div></div></div></div><script>
${projectCaseRoots.toString()}
${projectRecovery.toString()}
const K=new URLSearchParams(location.search).get('k')||'', $=(id)=>document.getElementById(id), state={status:null,events:[],cases:new Map(),active:'',view:'case',session:'',lastCases:'',lastStream:'',lastRoots:'',lastRecovery:'',lastFrontier:'',lastWorkers:''}
const esc=(v)=>String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const caseOf=(e)=>String(e.session||e.sessionKey||e.caseId||e.task||(e.type&&e.type.startsWith('task-')?e.id:'')||'')
const timeOf=(e)=>new Date(e.at||e.t||Date.now()).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})
function remember(e){const id=caseOf(e);if(!id)return;const prior=state.cases.get(id)||{id,title:id,status:'Ready',caseId:'',roots:0};if(e.text)prior.title=String(e.text).slice(0,70);if(e.type==='task-start'&&prior.status==='Waiting')prior.status=prior.caseId?'Case active':'Ready';if(e.type==='case-state'){prior.caseId=e.caseId||prior.caseId;if(e.caseStatus==='closed'){prior.status='Ready';prior.caseId=''}else if(e.caseStatus==='paused')prior.status='Case paused';else if(e.caseStatus==='unavailable')prior.status='Case state unavailable';else if(e.caseStatus==='running')prior.status='Case active'}if(e.type==='focus'){const rs=Array.isArray(e.roots)?e.roots:[];prior.roots=rs.length;if(rs.length===0){if(prior.status!=='Detached'&&prior.status!=='Waiting'){prior.status='Ready';prior.caseId=''}}else prior.caseId=String(rs[0].caseId||prior.caseId)}if(e.type==='case-unfocused'&&prior.caseId===e.caseId){prior.caseId='';if(prior.status!=='Detached'&&prior.status!=='Waiting')prior.status='Ready'}if(e.type==='case-open'&&e.ok!==false){prior.status='Case active';prior.caseId=e.caseId||''}if(e.type==='case-pending'){prior.status='Waiting';prior.caseId=e.caseId||prior.caseId}if(e.type==='session-detached'){prior.status='Detached';prior.caseId=e.caseId||prior.caseId}if(e.type==='case-closed'){prior.status='Ready';prior.caseId=''}if(e.type==='task-done'&&e.activeCaseId){if(prior.caseId!==e.activeCaseId)prior.status='Case active';prior.caseId=e.activeCaseId}else if(e.type==='task-done'&&!prior.caseId)prior.status='Ready';state.cases.set(id,prior)}
function renderCases(){const root=$('cases'),oldTop=root.scrollTop;let html='<div class="case '+(state.active===''?'active':'')+'" data-case="">All activity</div>';for(const c of [...state.cases.values()].reverse())html+='<div class="case '+(state.active===c.id?'active':'')+'" data-case="'+esc(c.id)+'"><span>'+esc(c.title)+'</span><small>'+esc(c.status)+' · '+esc(c.id)+'</small></div>';if(html===state.lastCases)return;root.innerHTML=html;state.lastCases=html;root.scrollTop=oldTop;root.querySelectorAll('.case').forEach((n)=>n.onclick=()=>{state.active=n.dataset.case;if(n.dataset.case)state.session=n.dataset.case;render(true)})}
function eventBody(e){if(e.type==='case-state')return 'Case lifecycle: '+(e.caseStatus||'unavailable')+(e.root?' · root '+e.root:'')+(typeof e.gaps==='number'?' · '+e.gaps+' open gap(s)':'');if(e.type==='focus')return (e.roots||[]).length?'In focus: '+(e.roots||[]).map((r)=>r.caseId+' ('+r.status+')').join(' · '):'No Case is in focus.';if(e.type==='case-unfocused')return 'Released from this conversation\\'s focus. Its lifecycle on the Board is unchanged.';if(e.type==='affected')return (e.affectedCases||[]).length?'Affected Cases: '+e.affectedCases.join(' · '):'No live acceptance root advanced.';if(e.type==='recovery')return projectRecovery([{...e,src:'agent'}]).label;if(e.type==='handoff')return 'The outcome of an earlier '+(e.tool||'tool')+' call was handed to the model. That request executed nothing.';if(e.type==='blocked')return e.teaching||'This turn stopped without asking the model.';if(e.type==='queue-suspended')return e.notSent+' further call(s) proposed in that turn were not sent: an earlier call had an unknown outcome.';if(e.type==='artifact-read')return 'Artifact '+(e.ref||'')+' · '+(e.complete?'final fragment':'fragment')+(e.truncated?' · truncated at the read limit':'')+(e.mediaType?' · '+e.mediaType:'');if(e.type==='worker-activity-unavailable')return e.note||'This Runtime cannot yet report a dispatched invocation: the Agent Profile result has no published field carrying it. Follow the Action in Console.';if(e.type==='loss')return 'Bounded view: '+(e.omitted===undefined?'rows were':e.omitted+' row(s) were')+' omitted ('+(e.reason||'limit')+'). This answer is partial.';if(e.type==='propose')return e.say||JSON.stringify(e.tool||e.cmds||e.ops||{},null,2);if(e.type==='verdict')return e.accepted?'Accepted by Board'+(e.cmd?' · '+e.cmd:''):(e.teaching||'Rejected by Board');if(e.type==='source-plan')return (e.plans||[]).map((p)=>p.action+' via '+p.source+' → '+p.predicate).join('\\n');if(e.type==='claimed')return (e.kind||'work')+' · '+(e.id||'claimed');if(e.type==='reported')return (e.kind||'work')+' · '+(e.id||'')+' · '+(e.landed?'receipt committed':'receipt not committed')+(e.result?'\\n'+e.result:'')+(e.reason?'\\n'+e.reason:'');if(e.type==='case-open')return e.ok===false?'Case could not be opened':'Case Type '+(e.caseType||'exploration');if(e.type==='case-closed')return 'Disposition: '+(e.disposition||'closed');if(e.type==='case-pending')return e.reason||e.note||'Waiting for evidence';if(e.type==='session-detached')return e.note||'The local conversation was reclaimed; its Rulith Case remains on the Board.';if(e.type==='log')return e.line||'';return e.note||e.text||''}
function card(e,trace=false){const body=eventBody(e);if(!trace&&['case-state','focus','case-unfocused','affected','spawn','exit','up','log','start','round','task-queued','slot-open'].includes(e.type))return '';if(!trace&&(e.type==='task-start'||(e.type==='user'&&!e.interject)))return '<div class="message user"><div class="bubble">'+esc(e.text||'')+'</div></div>';if(!trace&&e.type==='propose'&&e.say)return '<div class="message"><div class="meta">Agent · '+timeOf(e)+'</div><div class="agent-text">'+esc(e.say)+'</div></div>';const good=e.accepted===true||e.landed===true||e.type==='case-closed',bad=e.accepted===false||e.landed===false||e.type==='error',cls=bad?'bad':good?'good':'warn';const label=({'case-state':'Case lifecycle','focus':'Cases in focus','case-unfocused':'Case released from focus','affected':'Affected Cases','loss':'Bounded view','recovery':'Unresolved call','handoff':'Earlier outcome handed over','blocked':'Turn stopped','queue-suspended':'Remaining calls not sent','artifact-read':'Artifact fragment read','worker-activity-unavailable':'Invocation reporting unavailable','case-open':'Rulith Case opened','case-closed':'Rulith Case closed','case-pending':'Rulith Case pending','session-detached':'Conversation detached','source-plan':'Source route','verdict':'Board decision','claimed':'Worker claimed','reported':'Worker receipt','task-done':'Agent turn finished','task-start':'Message','task-queued':'Message queued','slot-open':'Capacity available','up':'Runtime online','spawn':'Process started','exit':'Process exited','round':'Agent turn','log':'Runtime log','error':'Runtime error'})[e.type]||e.type.replaceAll('-',' ');return '<div class="message"><div class="event '+cls+'"><div class="event-head"><span class="ico">'+(e.src==='worker'?'⚙':'◇')+'</span><span class="kind">'+esc(label)+'</span><span class="right">'+esc(e.src)+' · '+timeOf(e)+'</span></div>'+(body?'<div class="event-body">'+esc(body)+'</div>':'')+'</div></div>'}
function renderInspector(filtered){const reversed=[...filtered].reverse();const rows=projectCaseRoots(filtered),rec=projectRecovery(filtered),recMarkup='<div class="item">'+esc(rec.label)+(rec.detail?'<small>'+esc(rec.detail)+'</small>':'')+'</div>';if(recMarkup!==state.lastRecovery){$('recovery').innerHTML=recMarkup;state.lastRecovery=recMarkup}const inFocus=rows.filter((r)=>r.focused),hasCase=rows.length>0;const countText=!hasCase?'Not in use':inFocus.length+' in focus'+(rows.length>inFocus.length?' · '+(rows.length-inFocus.length)+' released':'');if($('casecount').textContent!==countText)$('casecount').textContent=countText;const rootsMarkup=hasCase?rows.map((r)=>'<div class="item">'+esc(r.caseId)+' — '+esc(r.label)+'<small>'+(r.root?'root '+esc(r.root)+' · ':'')+esc(r.observation)+(r.gaps===null?'':' · '+r.gaps+' open gap(s)')+(r.focused?'':' · released from focus')+'</small></div>').join(''):'<div class="item">Rulith has not been used for this conversation.</div>';if(rootsMarkup!==state.lastRoots){$('roots').innerHTML=rootsMarkup;state.lastRoots=rootsMarkup}const plan=reversed.find((e)=>e.type==='source-plan'),frontierMarkup=plan&&plan.plans?.length?plan.plans.map((p)=>'<div class="item">'+esc(p.predicate)+'<small>'+esc(p.action)+' via '+esc(p.source)+'</small></div>').join(''):hasCase?'<div class="item">No frontier has been reported.</div>':'<div class="item">Rulith has not been used for this conversation.</div>';if(frontierMarkup!==state.lastFrontier){$('frontier').innerHTML=frontierMarkup;state.lastFrontier=frontierMarkup}const worker=filtered.filter((e)=>(e.src==='worker'&&(['claimed','reported','error','skip','up'].includes(e.type)||(e.type==='log'&&e.stderr)))||(e.src==='agent'&&e.type==='worker-activity-unavailable')).slice(-8).reverse(),workerMarkup=worker.length?worker.map((e)=>'<div class="item">'+esc(e.type==='up'?'Worker online':e.type==='worker-activity-unavailable'?'Invocation reporting unavailable · '+eventBody(e):eventBody(e))+'<small>'+timeOf(e)+'</small></div>').join(''):'<div class="item">No Worker activity for this conversation.</div>';if(workerMarkup!==state.lastWorkers){$('workers').innerHTML=workerMarkup;state.lastWorkers=workerMarkup}}
function render(forceTail){const stream=$('stream'),oldTop=stream.scrollTop,stick=forceTail===true||stream.scrollHeight-stream.scrollTop-stream.clientHeight<80;renderCases();const filtered=state.events.filter((e)=>!state.active||caseOf(e)===state.active),cards=filtered.map((e)=>card(e,state.view==='trace')).filter(Boolean).join('');$('title').textContent=state.active?(state.cases.get(state.active)?.title||state.active):state.status?.mode==='worker'?'Worker activity':'Local activity';$('subtitle').textContent=state.active?state.active:'Conversation with optional Rulith Case tools';document.querySelectorAll('[data-view]').forEach((button)=>button.classList.toggle('active',button.dataset.view===state.view));const needsSetup=state.status&&(state.status.roles.includes('agent')&&!state.status.agent||state.status.roles.includes('worker')&&!state.status.worker);const heading=needsSetup?'Runtime is not ready':state.status?.mode==='worker'?'Worker is ready for governed work':'What would you like to discuss or handle?',copy=needsSetup?'Inspect Trace and Runtime details, then edit the configured file or secret manager and restart the role.':state.status?.mode==='worker'?'Claims, Tool execution, and receipts will appear here.':'Chat normally. The Agent will use Rulith when governed work, evidence, or an auditable Case is useful.',markup=cards||'<div class="empty"><h1>'+heading+'</h1><p>'+copy+'</p></div>';if(markup!==state.lastStream){stream.innerHTML=markup;state.lastStream=markup;stream.scrollTop=stick?stream.scrollHeight:oldTop}else if(stick)stream.scrollTop=stream.scrollHeight;renderInspector(filtered)}
function showRuntime(r){const a=r.runtime?.agent||{},w=r.runtime?.worker||{};$('agentname').textContent='Agent Runtime';$('agentidentity').textContent=a.id||'not configured';$('modelbadge').textContent=a.model||'No model';$('thinkingbadge').textContent=a.thinking==='extended'?'Extended thinking':'Standard';$('toolbadge').textContent=r.roles.includes('worker')?'Rulith + Worker '+(w.workspaceTools||'read'):'Rulith MCP';$('detailagent').textContent=a.id||'—';$('detailagentkey').textContent=a.credentialConfigured?'Configured':'Missing';$('detailmodelurl').textContent=a.modelService||'—';$('detailmodel').textContent=a.model||'—';$('detailmodelkey').textContent=a.modelKeyConfigured?'Configured':'Not configured';$('detailthinking').textContent=a.thinking||'standard';$('detailconcurrency').textContent='serial · one connection';$('detailconnection').textContent=w.connection||'—';$('detailworkerkey').textContent=w.credentialConfigured?'Configured':'Missing';$('detailtools').textContent=w.workspaceTools||'read';$('detailtoolsfile').textContent=w.toolsFile||'built-in only';$('detailsourcesfile').textContent=w.sourcesFile||'none';$('detailconfig').textContent=r.runtime?.configFile||'—';document.querySelectorAll('[data-control]').forEach((button)=>button.hidden=!r.roles.includes(button.dataset.control))}
async function refresh(){const response=await fetch('/status?k='+encodeURIComponent(K)).catch(()=>null);if(response?.status===401||response?.status===403){location.reload();return}const r=await response?.json().catch(()=>null);if(!r||!r.ok)return;state.status=r;$('mode').textContent=r.mode;$('agentstate').textContent=r.roles.includes('agent')?(r.agent?'local online':'local off'):'not local';$('workerstate').textContent=r.roles.includes('worker')?(r.worker?'local online':'local off'):'not local';$('agentdot').className='dot '+(r.agent?'on':'');$('workerdot').className='dot '+(r.worker?'on':'');$('newcase').hidden=!r.roles.includes('agent');$('composer').hidden=!r.roles.includes('agent');$('app').classList.toggle('worker-only',r.mode==='worker');showRuntime(r);render()}
const es=new EventSource('/events?k='+encodeURIComponent(K));es.onmessage=(m)=>{const e=JSON.parse(m.data);state.events.push(e);remember(e);render()}
$('composer').addEventListener('submit',async(ev)=>{ev.preventDefault();const text=$('prompt').value.trim();if(!text)return;let businessKey;const raw=$('businesskey').value.trim();if(raw){try{businessKey=JSON.parse(raw)}catch{alert('Business key must be valid JSON.');return}}$('send').disabled=true;$('send').textContent='…';const r=await fetch('/cases?k='+encodeURIComponent(K),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text,caseType:$('casetype').value,...(state.session?{sessionKey:state.session}:{}),...(businessKey===undefined?{}:{businessKey})})}).then((x)=>x.json()).catch(()=>null);$('send').disabled=false;$('send').textContent='↑';if(!r?.ok){alert(r?.teaching||'The message could not be submitted.');return}$('prompt').value='';$('casepopover').hidden=true;if(r.sessionKey){state.session=r.sessionKey;state.active=r.sessionKey}render(true)})
$('newcase').onclick=()=>{state.session='';state.active='';state.view='case';render(true);$('prompt').focus()};$('clear').onclick=()=>{state.events=[];render(true)};$('prompt').addEventListener('keydown',(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('composer').requestSubmit()}});$('caseoptions').onclick=()=>{$('casepopover').hidden=!$('casepopover').hidden};document.addEventListener('click',(event)=>{if(!$('casepopover').hidden&&!$('casepopover').contains(event.target)&&event.target!==$('caseoptions'))$('casepopover').hidden=true});document.querySelectorAll('[data-view]').forEach((button)=>button.onclick=()=>{state.view=button.dataset.view;render(true)});$('exportlog').onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),mode:state.status?.mode,activeCase:state.active||null,events:state.events},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rulith-local-session-'+new Date().toISOString().replaceAll(':','-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const openRuntime=()=>{$('runtimemodal').hidden=false;$('runtimemsg').textContent='';refresh()},closeRuntime=()=>{$('runtimemodal').hidden=true}
$('runtimeopen').onclick=openRuntime;$('mobileruntime').onclick=openRuntime;$('modelbadge').onclick=openRuntime;$('runtimeclose').onclick=closeRuntime;$('runtimemodal').onclick=(event)=>{if(event.target===$('runtimemodal'))closeRuntime()};document.addEventListener('keydown',(event)=>{if(event.key==='Escape')closeRuntime()})
/* A start waits for the role to report that it finished initializing, which can take seconds.
   Say so while it is happening: a button that goes quiet for that long reads as a hung page,
   and the answer that follows is the host's own state word, not a guess made here. */
/* Only the states that answer ok:true need a word here; every other outcome carries the host's
   own teaching and that is what is printed. The unconfirmed and cancelled entries were
   unreachable for exactly that reason — and the cancelled one still said "was stopped", the
   claim the host teaching was corrected not to make about a process that has not exited.
   (No backticks in here: this whole script lives inside a template literal.) */
var CONTROL_SAID={ready:'started and reported ready.',stopped:'stopped.',stopping:'was sent the stop signal and has not exited yet.'}
document.querySelectorAll('[data-control]').forEach((button)=>button.onclick=async()=>{button.disabled=true;$('runtimemsg').textContent=button.dataset.operation==='start'?'Starting '+button.dataset.control+'; waiting for it to report ready…':'Stopping '+button.dataset.control+'…';const result=await fetch('/control?k='+encodeURIComponent(K),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({role:button.dataset.control,operation:button.dataset.operation})}).then((x)=>x.json()).catch(()=>null);$('runtimemsg').textContent=result?.ok?button.dataset.control+' '+(CONTROL_SAID[result.state]||(button.dataset.operation+'ed.')):(result?.teaching||'Runtime control failed.');button.disabled=false;setTimeout(refresh,300)})
const mcpLink=document.createElement('a');mcpLink.textContent='MCP services · install and configure';mcpLink.href='/mcp-services?k='+encodeURIComponent(K);mcpLink.className='settingsopen';mcpLink.style.cssText='display:block;color:var(--accent);margin-top:8px;text-decoration:none';$('runtimeopen').after(mcpLink);const mobileMcpLink=mcpLink.cloneNode(true);$('runtimemsg').before(mobileMcpLink)
refresh();setInterval(refresh,2500)
</script></body></html>`
